development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://<%= ENV['FCREPO_HOST'] || 'localhost' %>:<%= ENV['FCREPO_DEVELOPMENT_PORT'] || ENV['FCREPO_PORT'] || 8984 %>/rest
  base_path: <%= ENV['FCREPO_BASE_PATH'] || '/dev' %>
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://<%= ENV['FCREPO_HOST'] || 'localhost' %>:<%= ENV['FCREPO_TEST_PORT'] || ENV['FCREPO_PORT'] || 8986 %>/rest
  base_path: <%= ENV['FCREPO_BASE_PATH'] || '/test' %>
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://<%= ENV['FCREPO_HOST'] || 'localhost' %>:<%= ENV['FCREPO_PORT'] || 8983 %>/rest
  base_path: <%= ENV['FCREPO_BASE_PATH'] || '/prod' %>
